name: Auto Merge PR

on:
  pull_request:
    types: [opened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Wait a few seconds to ensure PR is ready
          sleep 5
          
          # Auto merge the PR
          gh pr merge "${{ github.event.pull_request.number }}" --auto --merge
