name: Issue Bot

on:
  issues:
    types: [opened]

jobs:
  update-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install aider
        run: |
          python -m pip install --upgrade pip
          python -m pip install aider-install
          aider-install
          
      - name: Create branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          BRANCH_NAME="fix/issue-${{ github.event.issue.number }}"
          git checkout -b $BRANCH_NAME
          
      - name: Update code with aider
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          # Create EDITS file from issue
          echo "Update the code based on this issue:" > EDITS
          echo "Title: ${{ github.event.issue.title }}" >> EDITS
          echo "Description: ${{ github.event.issue.body }}" >> EDITS
          
          # Run aider with the correct parameters
          aider --model openrouter/anthropic/claude-3.5-sonnet --message-file EDITS --yes-always
          
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="fix/issue-${{ github.event.issue.number }}"
          git push --force origin $BRANCH_NAME
          
          # Create PR
          gh pr create \
            --title "Fix Issue #${{ github.event.issue.number }}" \
            --body "This PR addresses issue #${{ github.event.issue.number }}" \
            --base main \
            --head $BRANCH_NAME
            
      - name: Merge Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="fix/issue-${{ github.event.issue.number }}"
          # Wait briefly for PR to be created
          sleep 5
          # Get PR number and merge it
          PR_NUMBER=$(gh pr list --head $BRANCH_NAME --json number -q '.[0].number')
          gh pr merge $PR_NUMBER --auto --merge
          
      - name: Close Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Add thank you comment and close the issue
          gh issue comment ${{ github.event.issue.number }} --body "Thank you for your issue! The changes have been merged."
          gh issue close ${{ github.event.issue.number }}
